from tkinter import *

cal = Tk()
cal.title("Calculator")
cal.minsize(width=320, height=500)

display = Entry(width=28, justify="right", background="lightgray", borderwidth=10)
display.place(x=0,y=0)
Button7 = Button(text="7", width=5, font="Arial")
Button7.grid(row=3, column=0)
Button4 = Button(text="4", width=5, font="Arial")
Button4.grid(row=4, column=0)
Button1 = Button(text="1", width=5, font="Arial")
Button1.grid(row=5, column=0)
Button0 = Button(text="0", width=5, font="Arial")
Button0.grid(row=6, column=0)
Button8 = Button(text="8", width=5, font="Arial")
Button8.grid(row=3, column=1)
Button5 = Button(text="5", width=5, font="Arial")
Button5.grid(row=4, column=1)
Button2 = Button(text="2", width=5, font="Arial")
Button2.grid(row=5, column=1)
Button00 = Button(text="00", width=5, font="Arial")
Button00.grid(row=6, column=1)
Button9 = Button(text="9", width=5, font="Arial")
Button9.grid(row=3, column=2)
Button6 = Button(text="6", width=5, font="Arial")
Button6.grid(row=4, column=2)
Button3 = Button(text="3", width=5, font="Arial")
Button3.grid(row=5, column=2)
Buttondot = Button(text=".", width=5, font="Arial")
Buttondot.grid(row=6, column=2)
Buttondiv = Button(text="/", width=5, font="Arial")
Buttondiv.grid(row=2, column=3)
Buttonmul = Button(text="*", width=5, font="Arial")
Buttonmul.grid(row=3, column=3)
Buttonmin = Button(text="-", width=5, font="Arial")
Buttonmin.grid(row=4, column=3)
Buttonplus = Button(text="+", width=5, font="Arial")
Buttonplus.grid(row=5, column=3)
Buttonequ = Button(text="=", width=5, font="Arial")
Buttonequ.grid(row=6, column=3)
cal.mainloop()
