data = [
    {
        "name": "Cristiano Ronaldo",
        "followers_millions": 651,
        "profession": "Footballer",
        "origin": "Portugal",
    },
    {
        "name": "Lionel Messi",
        "followers_millions": 505,
        "profession": "Footballer",
        "origin": "Argentina",
    },
    {
        "name": "Selena Gomez",
        "followers_millions": 421,
        "profession": "Singer/Actress",
        "origin": "USA",
    },
    {
        "name": "Kylie Jenner",
        "followers_millions": 394,
        "profession": "Entrepreneur/TV Personality",
        "origin": "USA",
    },
    {
        "name": "Dwayne Johnson",
        "followers_millions": 394,
        "profession": "Actor/Wrestler",
        "origin": "USA",
    },
    {
        "name": "Ariana Grande",
        "followers_millions": 376,
        "profession": "Singer/Actress",
        "origin": "USA",
    },
    {
        "name": "Kim Kardashian",
        "followers_millions": 353,
        "profession": "Entrepreneur/TV Personality",
        "origin": "USA",
    },
    {
        "name": "Beyoncé",
        "followers_millions": 305,
        "profession": "Singer",
        "origin": "USA",
    },
    {
        "name": "Khloé Kardashian",
        "followers_millions": 304,
        "profession": "TV Personality",
        "origin": "USA",
    },
    {
        "name": "Justin Bieber",
        "followers_millions": 286,
        "profession": "Singer",
        "origin": "Canada",
    },
    {
        "name": "Kendall Jenner",
        "followers_millions": 285,
        "profession": "Model",
        "origin": "USA",
    },
    {
        "name": "Taylor Swift",
        "followers_millions": 255,
        "profession": "Singer-Songwriter",
        "origin": "USA",
    },
    {
        "name": "Jennifer Lopez",
        "followers_millions": 242,
        "profession": "Singer/Actress",
        "origin": "USA",
    },
    {
        "name": "Virat Kohli",
        "followers_millions": 246,
        "profession": "Cricketer",
        "origin": "India",
    },
    {
        "name": "Neymar Jr",
        "followers_millions": 208,
        "profession": "Footballer",
        "origin": "Brazil",
    },
    {
        "name": "Miley Cyrus",
        "followers_millions": 205,
        "profession": "Singer/Actress",
        "origin": "USA",
    },
    {
        "name": "Zendaya",
        "followers_millions": 200,
        "profession": "Actress/Singer",
        "origin": "USA",
    },
    {
        "name": "Nicki Minaj",
        "followers_millions": 190,
        "profession": "Rapper/Singer",
        "origin": "Trinidad & Tobago",
    },
    {
        "name": "Kourtney Kardashian",
        "followers_millions": 180,
        "profession": "TV Personality",
        "origin": "USA",
    },
    {
        "name": "Cardi B",
        "followers_millions": 170,
        "profession": "Rapper",
        "origin": "USA",
    },
]
